ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER GRC_APP IDENTIFIED BY "AppPassword123";

GRANT CREATE SESSION TO GRC_APP;

GRANT SELECT ON IT_ASSETS TO GRC_APP;

GRANT EXECUTE ON GRC_ASSET_MANAGER TO GRC_APP;